FROM apache/airflow:3.3.1-python3.12

USER root

# Java 17 -- requis par PySpark, meme version qu'en local.
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jdk-headless procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow

COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir --no-warn-script-location \
    -r /tmp/requirements.txt apache-airflow-providers-standard
COPY dags/ /opt/airflow/dags/
COPY src/ /opt/airflow/project/src/
